#' generatePCAPlotsClass
#' @description generates PCA plot for each analytical platform
#' @author Lea Saxton \email{lea.saxton.831@@cranfield.ac.uk}
#' @param dataSet dataFrame from the data file generated by analytical platform
#' @param outputDir output directory name provided by the use in config json file
#' @param platform manalytical platform name
#' @import viridis shape ggplot2
#'
#' @examples
#' \dontrun{generatePCAPlotsClass(dataSet, outputDir, platform)}

generatePCAPlotsClass <- function(dataSet, outputDir, platform, method) {
        cat("generatePCAPlotsClass is starting \n")

        if (!file.exists(outputDir))
                dir.create(path = outputDir, showWarnings = FALSE)

        outputDir <- paste0(outputDir, "/PCAPlots")
        if (!file.exists(outputDir))
                dir.create(path = outputDir, showWarnings = FALSE)

        # Remove rows with infinite or missing values
        dataSet <- dataSet[complete.cases(dataSet), ]
        sensory <- "sensory_score"
        colorVar <- dataSet[, "sensory"]

        # Convert colorVar to a factor (treat sensory scores as categorical classes)
        colorVar <- as.factor(colorVar)

        sam <- row.names(dataSet)
        varb <- colnames(dataSet)
        X <- as.matrix(dataSet)

        cat("\nAuto-scaled\n===========\n")
        aPCAMODEL <- prcomp(dataSet, scale. = TRUE)

        aSC <- aPCAMODEL$x
        aSC <- as.data.frame(aSC)
        aLD <- aPCAMODEL$rotation
        aEV <- aPCAMODEL$sdev^2

        # calculate % variance for first 3 PCs
        variance <- c(aEV[1] / sum(aEV) * 100,
                      aEV[2] / sum(aEV) * 100,
                      aEV[3] / sum(aEV) * 100)

        outputFile <- paste0(outputDir, "/", platform,"_",method,"_PCA.pdf")
        pdf(outputFile)


        # Manually define colors for each category in colorVar
        color_palette <- c("red", "blue", "green", "purple", "orange")  # Add more colors as needed

        p <- ggplot(aSC, aes(PC1, PC2)) +
                geom_point(size = 4, aes(colour = colorVar)) +
                xlab(sprintf("PC1 (%1.0f%%)", variance[1])) +
                ylab(sprintf("PC2 (%1.0f%%)", variance[2])) +
                labs(title = paste0("PCA with ", platform, " dataset coloured by ", sensory)) +
                scale_color_manual(values = color_palette, name = sensory) +  # Use scale_color_manual with manual colors
                theme_bw()

        print(p)
        dev.off()
        cat("generatePCAPlotsClass function is finished \n")
}



mncn <- function(X) {
        ndim <- dim(X)
        m = ndim[1]
        meanx <- apply(X,2,mean)
        ONE <- matrix(1,m,1)
        mx <- (X - (ONE %*% meanx))
        return(mx)
}

